CREATE TABLE Product(
Id INT IDENTITY(1,1),
Name VARCHAR(100),
Description VARCHAR(200),
Image VARCHAR(MAX),
Colors VARCHAR(MAX),
CONSTRAINT pk_Product PRIMARY KEY (Id)
);


-- Script as CREATE


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NULL,
	[Description] [varchar](200) NULL,
	[Image] [varchar](max) NULL,
	[Colors] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Product] ADD  CONSTRAINT [pk_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
