CREATE TABLE Bid(
Id INT IDENTITY(1,1),
Price INT,
IdProducto INT,
CONSTRAINT pk_Bid PRIMARY KEY (Id),
CONSTRAINT fk_Product_Bid FOREIGN KEY (IdProducto) REFERENCES Product(Id)
);



-- Script as CREATE 


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bid](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Price] [int] NULL,
	[IdProducto] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bid] ADD  CONSTRAINT [pk_Bid] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bid]  WITH CHECK ADD  CONSTRAINT [fk_Product_Bid] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[Bid] CHECK CONSTRAINT [fk_Product_Bid]
GO
